version: '3'

services:
  db:
    image: postgres:16.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWROD}
      POSTGRES_DB: ${DB_NAME}
    container_name: teslo-db
    volumes:
      - ./postgres:/var/lib/postgresql/data


